//
// Created by Mekhail on 12.11.2020.
//

#ifndef DYNAMIC_CALCULATOR_ERROR_H
#define DYNAMIC_CALCULATOR_ERROR_H

enum Error
{
    ERR_OK,
    ERR_ARGS,
    ERR_DLL_NOT_VALID,
    ERR_DLL_FORMAT,
    ERR_TOKEN,
    ERR_EXPRESSION
};

#endif //DYNAMIC_CALCULATOR_ERROR_H
